# Generated by Django 4.2.1 on 2024-03-09 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='croud',
            old_name='salary',
            new_name='sal',
        ),
    ]
